# Generated by Django 3.0.5 on 2020-04-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='deleted',
            new_name='archived',
        ),
        migrations.AddField(
            model_name='todo',
            name='shreded',
            field=models.BooleanField(default=False),
        ),
    ]
